### ISSUE TITLE
Some jobs don't show in job history

### ISSUE THREAD

**Issue by hawkseye76** [ironmansoftware/universal-automation#167]
Job history for some reason omits recent jobs from history list.

**Comment by adamdriscoll** [comment]
I think we may have a problem with the groom job pruning jobs it shouldn't big. Do you happen to have a log in C:\ProgramData\UniversalAutomation\logs?

**Comment by hawkseye76** [comment]
[logs.zip](https://github.com/ironmansoftware/universal-automation/files/4450747/logs.zip)
Here is a copy of several days worth of logs with a screen shot of what i see in the jobs screen

**Comment by hawkseye76** [comment]
Just kinda watching this for a few day, looks like its cleaning up jobs every hour instead of based on the number of jobs to keep.

**Comment by adamdriscoll** [comment]
Hey @pshellguruwannabe,

Just a heads up that I haven't been able to reproduce this myself but I've added more logging into the 1.3 version that we just released. I was hoping that you could do me a favor and upgrade to that and grab the logs once again for me to review. 

Thanks so much for your help.

**Comment by hawkseye76** [comment]
> Hey @pshellguruwannabe,
> 
> Just a heads up that I haven't been able to reproduce this myself but I've added more logging into the 1.3 version that we just released. I was hoping that you could do me a favor and upgrade to that and grab the logs once again for me to review.
> 
> Thanks so much for your help.

Don't mind at all.  I don't see the upgrade yet, but when it pops up, i'll run in and put some logs out later.

Thanks

**Comment by hawkseye76** [comment]
Here is a log for today.  It's still deleting all current jobs hourly.  I have my job history set to 50.  
I think i see what is going on.  I have jobs dated on Apr. 6 still showing up in history for some reason.  looks like it might be seeing those, and that is where it's getting the 50 jobs from, but it's deleting the most current jobs instead of the oldest.  

[log20200416.txt](https://github.com/ironmansoftware/universal-automation/files/4489560/log20200416.txt)

**Comment by adamdriscoll** [comment]
@pshellguruwannabe - That's exactly what was happening. Thanks for the help! I've just committed a fix and this will be in v1.3.1
