### ISSUE TITLE
Porwershell version Arguments not saved

### ISSUE THREAD

**Issue by pminnebach** [ironmansoftware/universal-automation#71]
#### Describe the Issue

When i want to modify the config of the powershell versions to add an argument `-noprofile`, it doesn't save the argument. The same happens when adding a new powershell version. The Version and Path are saved, but not the argument.

#### Expected behavior

It should save the argument. :)

#### Screenshots

![image](https://user-images.githubusercontent.com/4376572/72459405-016c8780-37cb-11ea-9530-e0e1cdb8d637.png)

![image](https://user-images.githubusercontent.com/4376572/72459435-12b59400-37cb-11ea-9477-ae3ba4e32733.png)

#### Script Sample

Attempt to attach sample code that will allow others to reproduce the issue. **NOTE**: Generally speaking this is the **MOST EFFECTIVE** way to have your issue resolved.

#### Version Information

- **Host Operating System**: Microsoft Windows Server 2019 Standard Build 17763
- **Host PowerShell Version**: PowerShell Core 6.2.3
- **Universal Automation Version**: 0.0.3
- **Universal Dashboard Version**: 2.8.1
- **UD Hosting Method**: PowerShell

**Comment by Windos** [comment]
Not in a position to test myself, but interested to know.

Does the function return the arguments: `Get-UAPowerShellVersion`

If you add a new PS version via the function, does it stick: `New-UAPowerShellVersion`

Just wondering if it's a disconnect between UD and the UA server.

**Comment by leeberg** [comment]
Nope - just wasn't implemented properly.

Currently testing fixes - will be merged shortly

**Comment by leeberg** [comment]
Merged!

**Comment by pminnebach** [comment]
It still isn't solved for me.

I still can't edit the arguments from the dashboard. But when i add a new one via the powershell gui, it does show the correct argument.

Also, with a fresh setup, it shows my complete $profile output.

I verified all this by deleting the modules completely and the localappdata folders.

![image](https://user-images.githubusercontent.com/4376572/72506768-d7ef4280-3842-11ea-971a-f51b95b10158.png)

@leeberg

**Comment by leeberg** [comment]
@pminnebach  - right you are! 

Sorry I got the fixes merged but it's not in a new build of UA yet - I'll keep this open and post once that build is release.

**Comment by adamdriscoll** [comment]
I can fix that profile thing. We get the PS version by launching PS and running $PSVersionTable but we must not be passing -NoProfile. 

Unless you got that too @leeberg ?

NVM: It's not fixed yet. Will fix.

**Comment by adamdriscoll** [comment]
Going to mark this as resolved since it's committed. I've updated the changelog to include unreleased changes: https://github.com/ironmansoftware/universal-automation/blob/master/CHANGELOG.md
